// Note: baseURL already includes '/api', so endpoints should not start with '/api'
export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    CHANGE_PASSWORD: '/auth/change-password',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    UPDATE_PROFILE: '/auth/profile',
    GET_USER: (id) => `/auth/user/${id}`,
  },
  USERS: {
    GET_ALL: '/admin/users',
    GET_BY_ID: (id) => `/admin/users/${id}`,
    CREATE: '/admin/users',
    UPDATE: (id) => `/admin/users/${id}`,
    DELETE: (id) => `/admin/users/${id}`,
  },
  PATIENTS: {
    GET_ALL: '/patient',
    GET_BY_ID: (id) => `/patient/${id}`,
    GET_BY_USER_ID: (userId) => `/patient/by-user/${userId}`,
    CREATE: '/patient',
    UPDATE: (id) => `/patient/${id}`,
    DELETE: (id) => `/patient/${id}`,
  },
  DOCTORS: {
    GET_ALL: '/doctor',
    GET_BY_ID: (id) => `/doctor/${id}`,
    GET_BY_USER_ID: (userId) => `/doctor/by-user/${userId}`,
    CREATE: '/doctor',
    UPDATE: (id) => `/doctor/${id}`,
    DELETE: (id) => `/doctor/${id}`,
    APPROVE: (id) => `/doctor/${id}/approve`,
  },
  APPOINTMENTS: {
    GET_ALL: '/appointment',
    GET_BY_ID: (id) => `/appointment/${id}`,
    CREATE: '/appointment',
    UPDATE: (id) => `/appointment/${id}`,
    DELETE: (id) => `/appointment/${id}`,
    CANCEL: (id) => `/appointment/${id}/cancel`,
    CAN_START_CONSULTATION: (id) => `/appointment/${id}/can-start-consultation`,
  },
  PAYMENTS: {
    GET_ALL: '/payment',
    GET_BY_ID: (id) => `/payment/${id}`,
    INITIATE: '/payment/initiate',
    CALLBACK: '/payment/callback',
    GET_BY_DOCTOR: (doctorId) => `/payment/doctor/${doctorId}`,
    REFUND: (id) => `/payment/${id}/refund`,
    DOWNLOAD_INVOICE: (id) => `/payment/${id}/invoice`,
    STATS: '/payment/stats',
  },
  MEDICAL_RECORDS: {
    GET_ALL: '/medicalrecord',
    GET_BY_ID: (id) => `/medicalrecord/${id}`,
    CREATE: '/medicalrecord',
    UPDATE: (id) => `/medicalrecord/${id}`,
    DELETE: (id) => `/medicalrecord/${id}`,
  },
  TREATMENT_PLANS: {
    GET_ALL: '/treatmentplan',
    GET_BY_ID: (id) => `/treatmentplan/${id}`,
    CREATE: '/treatmentplan',
    UPDATE: (id) => `/treatmentplan/${id}`,
    DELETE: (id) => `/treatmentplan/${id}`,
  },
  MOOD_LOGS: {
    GET_ALL: '/moodlog',
    GET_BY_PATIENT_ID: (patientId) => `/moodlog/patient/${patientId}`,
    GET_BY_ID: (id) => `/moodlog/${id}`,
    CREATE: '/moodlog',
    UPDATE: (id) => `/moodlog/${id}`,
    DELETE: (id) => `/moodlog/${id}`,
  },
  FEEDBACK: {
    GET_ALL: '/feedback',
    GET_BY_ID: (id) => `/feedback/${id}`,
    CREATE: '/feedback',
    UPDATE: (id) => `/feedback/${id}`,
    DELETE: (id) => `/feedback/${id}`,
    APPROVE: (id) => `/feedback/${id}/approve`,
    RESPOND: (id) => `/feedback/${id}/respond`,
  },
  MESSAGES: {
    GET_ALL: '/message',
    GET_BY_ID: (id) => `/message/${id}`,
    SEND: '/message',
    UPDATE: (id) => `/message/${id}`,
    DELETE: (id) => `/message/${id}`,
  },
  NOTIFICATIONS: {
    GET_ALL: '/notification',
    GET_BY_ID: (id) => `/notification/${id}`,
    MARK_READ: (id) => `/notification/${id}/read`,
    MARK_ALL_READ: '/notification/mark-all-read',
    UNREAD_COUNT: '/notification/unread-count',
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard/stats',
    USERS: '/admin/users',
    DOCTORS: '/admin/doctors',
    MESSAGES: '/admin/messages',
    ACTIVATE_USER: (id) => `/admin/users/${id}/activate`,
    DEACTIVATE_USER: (id) => `/admin/users/${id}/deactivate`,
    RESET_USER_PASSWORD: (id) => `/admin/users/${id}/reset-password`,
  },
};

export default API_ENDPOINTS;

